// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetServerOutput():Promise<string>;

export function GetServerStatus():Promise<string>;

export function StartGinServer(arg1:string):Promise<string>;

export function StopGinServer():Promise<string>;
