// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function GetAllProcessStatus():Promise<Record<string, string>>;

export function GetProcessOutput(arg1:string):Promise<string>;

export function GetProcessStatus(arg1:string):Promise<string>;

export function GetRegisteredProcesses():Promise<Array<string>>;

export function GetServerOutput():Promise<string>;

export function GetServerStatus():Promise<string>;

export function RegisterProcess(arg1:string,arg2:main.ProcessConfig):Promise<void>;

export function StartGinServer(arg1:string):Promise<string>;

export function StartProcess(arg1:string,arg2:Array<string>):Promise<string>;

export function StopGinServer():Promise<string>;

export function StopProcess(arg1:string):Promise<string>;
