// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllProcessStatus() {
  return window['go']['main']['App']['GetAllProcessStatus']();
}

export function GetConfig() {
  return window['go']['main']['App']['GetConfig']();
}

export function GetConfigInfo() {
  return window['go']['main']['App']['GetConfigInfo']();
}

export function GetEduExpConfig() {
  return window['go']['main']['App']['GetEduExpConfig']();
}

export function GetGlobalConfig() {
  return window['go']['main']['App']['GetGlobalConfig']();
}

export function GetLicenseConfig() {
  return window['go']['main']['App']['GetLicenseConfig']();
}

export function GetProcessOutput(arg1) {
  return window['go']['main']['App']['GetProcessOutput'](arg1);
}

export function GetProcessStatus(arg1) {
  return window['go']['main']['App']['GetProcessStatus'](arg1);
}

export function GetRegisteredProcesses() {
  return window['go']['main']['App']['GetRegisteredProcesses']();
}

export function GetServerOutput() {
  return window['go']['main']['App']['GetServerOutput']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetWorkflowConfig() {
  return window['go']['main']['App']['GetWorkflowConfig']();
}

export function RegisterProcess(arg1, arg2) {
  return window['go']['main']['App']['RegisterProcess'](arg1, arg2);
}

export function ResetConfig() {
  return window['go']['main']['App']['ResetConfig']();
}

export function StartGinServer(arg1) {
  return window['go']['main']['App']['StartGinServer'](arg1);
}

export function StartProcess(arg1, arg2) {
  return window['go']['main']['App']['StartProcess'](arg1, arg2);
}

export function StopGinServer() {
  return window['go']['main']['App']['StopGinServer']();
}

export function StopProcess(arg1) {
  return window['go']['main']['App']['StopProcess'](arg1);
}

export function UpdateEduExpConfig(arg1) {
  return window['go']['main']['App']['UpdateEduExpConfig'](arg1);
}

export function UpdateGlobalConfig(arg1) {
  return window['go']['main']['App']['UpdateGlobalConfig'](arg1);
}

export function UpdateLicenseConfig(arg1) {
  return window['go']['main']['App']['UpdateLicenseConfig'](arg1);
}

export function UpdateWorkflowConfig(arg1) {
  return window['go']['main']['App']['UpdateWorkflowConfig'](arg1);
}
