// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GetAllProcessStatus() {
  return window['go']['main']['App']['GetAllProcessStatus']();
}

export function GetAppDataDir() {
  return window['go']['main']['App']['GetAppDataDir']();
}

export function GetConfigFilePath() {
  return window['go']['main']['App']['GetConfigFilePath']();
}

export function GetConfigInfo() {
  return window['go']['main']['App']['GetConfigInfo']();
}

export function GetEduExpConfig() {
  return window['go']['main']['App']['GetEduExpConfig']();
}

export function GetEduToolsOutput() {
  return window['go']['main']['App']['GetEduToolsOutput']();
}

export function GetEduToolsStatus() {
  return window['go']['main']['App']['GetEduToolsStatus']();
}

export function GetFullConfig() {
  return window['go']['main']['App']['GetFullConfig']();
}

export function GetGlobalConfig() {
  return window['go']['main']['App']['GetGlobalConfig']();
}

export function GetLicenseConfig() {
  return window['go']['main']['App']['GetLicenseConfig']();
}

export function GetProcessOutput(arg1) {
  return window['go']['main']['App']['GetProcessOutput'](arg1);
}

export function GetProcessStatus(arg1) {
  return window['go']['main']['App']['GetProcessStatus'](arg1);
}

export function GetRegisteredProcessNames() {
  return window['go']['main']['App']['GetRegisteredProcessNames']();
}

export function GetRegisteredProcesses() {
  return window['go']['main']['App']['GetRegisteredProcesses']();
}

export function GetServerOutput() {
  return window['go']['main']['App']['GetServerOutput']();
}

export function GetServerStatus() {
  return window['go']['main']['App']['GetServerStatus']();
}

export function GetWorkflowConfig() {
  return window['go']['main']['App']['GetWorkflowConfig']();
}

export function GetWorkflowUIOutput() {
  return window['go']['main']['App']['GetWorkflowUIOutput']();
}

export function GetWorkflowUIStatus() {
  return window['go']['main']['App']['GetWorkflowUIStatus']();
}

export function RegisterProcess(arg1, arg2) {
  return window['go']['main']['App']['RegisterProcess'](arg1, arg2);
}

export function ResetConfigToDefault() {
  return window['go']['main']['App']['ResetConfigToDefault']();
}

export function StartEduTools(arg1) {
  return window['go']['main']['App']['StartEduTools'](arg1);
}

export function StartGinServer(arg1) {
  return window['go']['main']['App']['StartGinServer'](arg1);
}

export function StartProcess(arg1, arg2) {
  return window['go']['main']['App']['StartProcess'](arg1, arg2);
}

export function StartWorkflowUI(arg1) {
  return window['go']['main']['App']['StartWorkflowUI'](arg1);
}

export function StopEduTools() {
  return window['go']['main']['App']['StopEduTools']();
}

export function StopGinServer() {
  return window['go']['main']['App']['StopGinServer']();
}

export function StopProcess(arg1) {
  return window['go']['main']['App']['StopProcess'](arg1);
}

export function StopWorkflowUI() {
  return window['go']['main']['App']['StopWorkflowUI']();
}

export function UpdateEduExpConfig(arg1) {
  return window['go']['main']['App']['UpdateEduExpConfig'](arg1);
}

export function UpdateGlobalConfig(arg1) {
  return window['go']['main']['App']['UpdateGlobalConfig'](arg1);
}

export function UpdateLicenseConfig(arg1) {
  return window['go']['main']['App']['UpdateLicenseConfig'](arg1);
}

export function UpdateWorkflowConfig(arg1) {
  return window['go']['main']['App']['UpdateWorkflowConfig'](arg1);
}
